### PR TITLE
Add a GitHubStatus

### LINKED ISSUE #5: Report Tahoe-LAFS build status to GitHub
Tahoe-LAFS code is hosted on GitHub now.  GitHub PRs are used for much of its development.  Travis, Appveyor, and LGTM report their build results with the native GitHub PR build status UI.  Buildbot doesn't, though.  The situation overall creates the false impression of green CI when Buildbot builds may all be red.

Tahoe-LAFS buildbot should report its build results to GitHub so they appear alongside Travis et al.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #5

### CODE REVIEW

**Comment by warner** [comment]
sounds good to me, does this add a per-commit status message, or a per-PR?

**Comment by warner** [comment]
looks like per-commit, and GitHub shows the checkmark/X anywhere it shows the commit (so both the all-commits view, and the commits within a given PR)

**Comment by exarkun** [comment]
GitHubStatus needed a little bit of help.  I've tested this out now, though, and it seems to be producing good results.

It only reports statuses for builders with the "supported" tag.  I briefly considered having it report all statuses but mark only "supported" build statuses as required but it's not clear that's actually a feature you can have unless you are doing a tighter integration with github than buildbot is doing.  So I gave up on that.

It puts an in-progress status while the build runs and changes it to success/failure when it finished.

It creates a different status for each builder and updates them independently so it's also possible to see which ones have which states from the github ui.

**Comment by exarkun** [comment]
And as of just now, the results can be seen on https://github.com/tahoe-lafs/tahoe-lafs/commits/master - the top commit, "Merge pull request #486 from exarkun/2915.disable-hypothesis-deadline"

Notice there are two "buildbot/..." statuses (there is also a "default" status left over from testing earlier versions of the code).  Also notice the statuses have my github icon because I added a github token from my github account for the buildmaster to use to make the necessary API calls.  This could be a token from another account if there's one that's more appropriate.  It needs to be an account with push permission to tahoe-lafs/tahoe-lafs, I believe (a bot account would make the most sense I guess, if there is already such an account it's probably worth swapping the token; if not, eh, I can live with this token belonging to my account).

**Pull request merged**
